name: kiosk_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.0.0
  iconly: ^1.0.1
  lottie: ^3.1.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/image/

  fonts:
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/PlusJakartaSans-Light.ttf
        weight: 300
      - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
        weight: 600